[package]
name = "irdopto-im12xx"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rmodbus = { version = "0.5", features = ["nostd", "smallcontext"] }
serialport = "4.0"
fixedvec = "0.2"
